-- 문제 1
SELECT *
FROM EMPLOYEE
WHERE JOB = 'MANAGER'
ORDER BY ENAME;

-- 문제 2
SELECT ENAME, DNO
FROM EMPLOYEE
WHERE DNO IN(20,30)
ORDER BY ENAME DESC;

-- 문제 3 
SELECT ENAME, SALARY, DNO
FROM EMPLOYEE
WHERE SALARY BETWEEN 2000 AND 3000
AND DNO IN (20, 30)
ORDER BY ENAME ASC;

-- 문제 4
SELECT ENAME
FROM EMPLOYEE
WHERE ENAME LIKE '%A%'
AND ENAME LIKE '%E%';

-- 문제 5
SELECT *
FROM EMPLOYEE
WHERE DNO IN (20, 30)
AND SALARY > 2000;

-- 문제 6
SELECT EMPLOYEE.DNO, DEPARTMENT.DNAME
FROM EMPLOYEE, DEPARTMENT
WHERE EMPLOYEE.DNO = DEPARTMENT.DNO
AND EMPLOYEE.ENAME = 'SCOTT';